version: '3'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cyber_konsultant_test

  php:
    build:
      context: ./
      args:
        CI_REGISTRY_IMAGE: ${CI_REGISTRY_IMAGE}
    environment:
      APP_ENV: test
      DATABASE_URL: pgsql://postgres:postgres@postgres/cyber_konsultant_test
    depends_on:
      - postgres
    links:
      - postgres
    command: composer run-script phpunit

