version: '3'

services:
    postgres:
        image: postgres:12
        ports:
            - 5432:5432
        environment:
            TZ: Europe/Warsaw
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: cyber_konsultant
        volumes:
            - postgres:/var/lib/postgresql/data

    php:
        build:
            context: ./
            args:
                CI_REGISTRY_IMAGE: ${CI_REGISTRY_IMAGE}
                XDEBUG_ENABLED: 1
        depends_on:
            - postgres
        links:
            - postgres
        ports:
            - 8081:80
        volumes:
            - ./:/var/www/

volumes:
    postgres:
